<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Qcentris-396" failures="1" tests="3" name="tests.ErrorValidationTest" time="5.067" errors="0" timestamp="2024-12-30T01:26:47 EET" skipped="1">
  <testcase classname="tests.ErrorValidationTest" name="testWrongSelectedProduct" time="4.298"/>
  <system-out/>
  <testcase classname="tests.ErrorValidationTest" name="testInvalidLoginLandingPage" time="0.355">
    <failure message="The following asserts failed:
	Error message does not match the expected text. (Expected: &quot;Epic sadface:  is required&quot;, Found: &quot;Epic sadface: Password is required&quot;) expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error message does not match the expected text. (Expected: "Epic sadface:  is required", Found: "Epic sadface: Password is required") expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at utils.AssertionFactory.assertAll(AssertionFactory.java:43)
at tests.ErrorValidationTest.testInvalidLoginLandingPage(ErrorValidationTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- testInvalidLoginLandingPage -->
  <system-out/>
  <testcase classname="tests.ErrorValidationTest" name="testInvalidLoginLandingPage" time="0.414">
    <skipped/>
  </testcase> <!-- testInvalidLoginLandingPage -->
  <system-out/>
</testsuite> <!-- tests.ErrorValidationTest -->
